spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: banking-user-service
          uri: lb://servicio-cliente
          predicates:
            - Path=/ms/cliente/**          
server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka/
