server:
    port: 8084
spring:
    cache: redis
    redis:
        host: localhost
        port: 6379
    data:
        mongodb:
            uri: mongodb+srv://xvris:xvris@cluster0.bpun4.mongodb.net/apibanca
            
resilience4j.circuitbreaker:
    instances:
        regUser:
            registerHealthIndicator: true
            slidingWindowSize: 100
        updUser:
            registerHealthIndicator: true
            slidingWindowSize: 100
        findUserbyDni:
            registerHealthIndicator: true
            slidingWindowSize: 100

resilience4j.retry:
    instances:
        regUser:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
        updUser:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
        findUserbyDni:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException

resilience4j.bulkhead:
    instances:
        regUser:
            maxConcurrentCalls: 10
        updUser:
            maxConcurrentCalls: 10
        findUserbyDni:
            maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    regUser:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
    updUser:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
    findUserbyDni:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
    instances:
        regUser:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        updUser:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        findUserbyDni:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100

resilience4j.timelimiter:
    instances:
        regUser:
            timeoutDuration: 2s
            cancelRunningFuture: true
        updUser:
            timeoutDuration: 2s
            cancelRunningFuture: true
        findUserbyDni:
            timeoutDuration: 2s

            cancelRunningFuture: true