server:
    port: 8084
spring:
    data:
        mongodb:
            database: apibanca
            port: 27017
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka/
