spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: banking-user-service
          uri: lb://banking-user-service
          predicates:
            - Path=/ms/cliente/**   
          filters:  
            - StripPrefix=2
server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka/
