<<<<<<< HEAD
server:
    port: 8086
spring:
    data:
        mongodb:
            uri: mongodb+srv://xvris:xvris@cluster0.bpun4.mongodb.net/apibanca

resilience4j.circuitbreaker:
    instances:
        fundTransfer:
            registerHealthIndicator: true
            slidingWindowSize: 100
        payment:
            registerHealthIndicator: true
            slidingWindowSize: 100

resilience4j.retry:
    instances:
        fundTransfer:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
        payment:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException

resilience4j.bulkhead:
    instances:
        fundTransfer:
            maxConcurrentCalls: 10
        payment:
            maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    fundTransfer:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
    payment:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
    instances:
        fundTransfer:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        payment:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100

resilience4j.timelimiter:
    instances:
        fundTransfer:
            timeoutDuration: 2s
            cancelRunningFuture: true
        payment:
            timeoutDuration: 2s
=======
server:
    port: 8086
spring:
    data:
        mongodb:
            uri: mongodb+srv://xvris:xvris@cluster0.bpun4.mongodb.net/apibanca

resilience4j.circuitbreaker:
    instances:
        fundTransfer:
            registerHealthIndicator: true
            slidingWindowSize: 100
        payment:
            registerHealthIndicator: true
            slidingWindowSize: 100

resilience4j.retry:
    instances:
        fundTransfer:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
        payment:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException

resilience4j.bulkhead:
    instances:
        fundTransfer:
            maxConcurrentCalls: 10
        payment:
            maxConcurrentCalls: 10

resilience4j.thread-pool-bulkhead:
  instances:
    fundTransfer:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
    payment:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
    instances:
        fundTransfer:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        payment:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100

resilience4j.timelimiter:
    instances:
        fundTransfer:
            timeoutDuration: 2s
            cancelRunningFuture: true
        payment:
            timeoutDuration: 2s
>>>>>>> 1a97363320a9d4293ca5565a1b19c280cd84a72e
            cancelRunningFuture: true