spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: banking-user-service
          uri: http://localhost:8084          
server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka/
