server:
    port: 8088
spring:
    cache: redis
    redis:
        host: localhost
        port: 6379
    data:
        mongodb:
            uri: mongodb+srv://xvris:xvris@cluster0.bpun4.mongodb.net/apibanca
